version: "3"
services:
    node:
        container_name: nodeapp
        restart: always
        build: productsBackend/.
        ports:
              - "4000:4000"
        links:
              - mongo

    mongo:
        container_name: mymongodatabase
        image: mongo
        ports:
              - "27018:27017"